'use client';
import {useEffect,useState} from 'react';
import Page from './Page';
type Status={configured:boolean;connected:boolean;databaseSelected:boolean;databaseId?:string|null;databaseAlias?:string|null;scopes?:string|null;tokenExpiresAt?:string|null;updatedAt?:string|null;projectPushConfigured?:boolean;projectPullConfigured?:boolean};
type DbRow={id:number|string;alias:string;admin?:boolean;expired?:boolean;dataAccessType?:string};
export default function AccurateIntegration(){
 const [st,setSt]=useState<Status|null>(null),[dbs,setDbs]=useState<DbRow[]>([]),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 async function load(){const r=await fetch('/api/accurate/status',{cache:'no-store'});setSt(await r.json())}
 useEffect(()=>{load();const q=new URLSearchParams(location.search);if(q.get('error'))setErr(q.get('error')||'');if(q.get('connected'))setMsg('OAuth berhasil. Silakan pilih database Accurate.')},[]);
 async function databases(){setBusy('db');setErr('');try{const r=await fetch('/api/accurate/databases',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal mengambil database');setDbs(j.databases||[])}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function selectDb(d:DbRow){setBusy(String(d.id));setErr('');try{const r=await fetch('/api/accurate/select-database',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:d.id,alias:d.alias})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal membuka database');setMsg(`Database ${d.alias} terhubung.`);setDbs([]);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function sync(){setBusy('sync');setErr('');setMsg('');try{const r=await fetch('/api/accurate/sync',{method:'POST'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Sync gagal');const text=(j.result||[]).map((x:any)=>`${x.entity}: ${x.error?'ERROR '+x.error:x.count+' data'}`).join(' • ');setMsg('Sync selesai. '+text);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 async function disconnect(){if(!confirm('Putuskan koneksi Accurate? Master yang sudah tersinkron tetap tersimpan.'))return;setBusy('disconnect');await fetch('/api/accurate/disconnect',{method:'POST'});setDbs([]);setMsg('Koneksi Accurate diputus.');setBusy('');await load()}
 const state=!st?.configured?'Belum Dikonfigurasi':!st.connected?'Siap Dihubungkan':!st.databaseSelected?'OAuth Terhubung':'Terhubung';
 return <Page title="Accurate Online" subtitle="OAuth, pemilihan database, dan sinkronisasi master Accurate Online.">
  <div className="toolbar">{st?.configured&&!st.connected&&<a className="btn" href="/api/accurate/connect">Hubungkan Accurate</a>}{st?.connected&&!st.databaseSelected&&<button className="btn" onClick={databases} disabled={!!busy}>{busy==='db'?'Memuat...':'Pilih Database'}</button>}{st?.databaseSelected&&<button className="btn" onClick={sync} disabled={!!busy}>{busy==='sync'?'Sinkronisasi...':'↻ Sync Sekarang'}</button>}{st?.connected&&<button className="btn secondary" onClick={disconnect} disabled={!!busy}>Putuskan Koneksi</button>}<span className="spacer"/><span className={'pill '+(st?.databaseSelected?'green':st?.connected?'amber':'gray')}>{state}</span></div>
  {err&&<div className="notice" style={{marginTop:16}}><b>Gagal:</b> {err}</div>}{msg&&<div className="notice" style={{marginTop:16}}>{msg}</div>}
  <div className="twocol section"><div className="card"><div className="callout"><div className="callouticon">A</div><div><b>Status Koneksi</b><p className="subtitle">{!st?.configured?'Isi ACCURATE_CLIENT_ID, ACCURATE_CLIENT_SECRET, dan ACCURATE_REDIRECT_URI di Railway.':!st.connected?'Credential tersedia. Klik Hubungkan Accurate untuk OAuth.':st.databaseSelected?`Database aktif: ${st.databaseAlias||st.databaseId}`:'OAuth berhasil. Pilih database yang akan dipakai.'}</p></div></div><div className="section"><div className="metric-label">Scope OAuth</div><p className="subtitle">{st?.scopes||'Mengikuti ACCURATE_SCOPES saat koneksi dibuat.'}</p></div></div>
  <div className="card"><b>Master yang disinkronkan</b><p className="subtitle">Customer · Vendor · Item. Project tetap bisa dibuat lokal. Pull/Push Project dapat diaktifkan dengan endpoint Project dari API Docs Accurate melalui environment variable.</p><div className="section"><span className={'pill '+(st?.projectPullConfigured?'green':'gray')}>Project Pull {st?.projectPullConfigured?'aktif':'belum'}</span> <span className={'pill '+(st?.projectPushConfigured?'green':'gray')}>Project Push {st?.projectPushConfigured?'aktif':'belum'}</span></div></div></div>
  {dbs.length>0&&<div className="card section"><div className="sectionhead"><h2>Pilih Database Accurate</h2><span className="pill gray">{dbs.length} database</span></div><div className="tablewrap"><table><thead><tr><th>Database</th><th>Akses</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{dbs.map(d=><tr key={String(d.id)}><td><b>{d.alias}</b><div className="muted">ID {d.id}</div></td><td>{d.dataAccessType|| (d.admin?'ADMIN':'-')}</td><td>{d.expired?<span className="pill amber">Expired</span>:<span className="pill green">Aktif</span>}</td><td><button className="btn small" disabled={!!busy||d.expired} onClick={()=>selectDb(d)}>{busy===String(d.id)?'Membuka...':'Gunakan Database'}</button></td></tr>)}</tbody></table></div></div>}
  <div className="card section"><div className="sectionhead"><h2>Urutan Koneksi</h2></div><p className="subtitle">1. Hubungkan Accurate → 2. Login dan Beri Akses → 3. Pilih database → 4. Sync Sekarang. Access token dan session disimpan terenkripsi menggunakan key yang diturunkan dari secret aplikasi.</p></div>
 </Page>
}
