'use client';
import {useEffect,useState} from 'react';import Page from './Page';
type P={id:string;code:string;name:string;description?:string|null;contractValue:any;status:string;accurateId?:string|null;lastSyncedAt?:string|null};
export default function ProjectMaster(){
 const [rows,setRows]=useState<P[]>([]),[open,setOpen]=useState(false),[edit,setEdit]=useState<P|null>(null),[msg,setMsg]=useState(''),[syncing,setSyncing]=useState(''),[pushConfigured,setPushConfigured]=useState(false);
 async function load(){const [p,s]=await Promise.all([fetch('/api/projects',{cache:'no-store'}),fetch('/api/accurate/status',{cache:'no-store'})]);setRows(await p.json());const st=await s.json();setPushConfigured(Boolean(st.projectPushConfigured))}
 useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();setMsg('');const x=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch('/api/projects',{method:edit?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit?{...x,id:edit.id}:x)});const j=await res.json();if(!res.ok){setMsg(j.error||'Gagal menyimpan');return}setOpen(false);setEdit(null);await load()}
 async function del(p:P){if(!confirm(`Hapus project ${p.code} — ${p.name}?`))return;const r=await fetch('/api/projects?id='+p.id,{method:'DELETE'});const j=await r.json();if(!r.ok){alert(j.error);return}load()}
 async function syncAll(){setSyncing('all');const r=await fetch('/api/accurate/sync',{method:'POST'}),j=await r.json();setSyncing('');if(!r.ok){alert(j.error||'Sync gagal');return}await load()}
 async function push(p:P){setSyncing(p.id);const r=await fetch('/api/accurate/projects/push',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:p.id})}),j=await r.json();setSyncing('');if(!r.ok){alert(j.error||'Push project gagal');return}await load()}
 function form(p?:P|null){setEdit(p||null);setOpen(true)}
 return <Page title="Project" subtitle="Bisa dibuat lokal dan langsung dipakai untuk RAB. Setelah Accurate terhubung, project dapat dipetakan atau dikirim ke Accurate jika endpoint Project diaktifkan.">
  <div className="toolbar"><button className="btn" onClick={()=>form()}>+ Project Baru</button><button className="btn secondary" onClick={syncAll} disabled={!!syncing}>{syncing==='all'?'Sync...':'↻ Sync Accurate'}</button><a className="btn secondary" href="/integrations/accurate">Koneksi Accurate</a><span className="spacer"/><span className="muted">{rows.length} project</span></div>
  {!pushConfigured&&<div className="notice section">Project lokal tetap dapat dipakai penuh. Untuk tombol “Kirim ke Accurate”, isi <b>ACCURATE_PROJECT_SAVE_PATH</b> sesuai endpoint Project/Proyek pada API Docs akun Accurate Anda.</div>}
  {open&&<div className="card"><form onSubmit={save}><div className="formgrid"><div className="field"><label>Kode Project</label><input name="code" required defaultValue={edit?.code||''}/></div><div className="field"><label>Nama Project</label><input name="name" required defaultValue={edit?.name||''}/></div><div className="field"><label>Nilai Kontrak</label><input name="contractValue" type="number" step="0.01" defaultValue={String(edit?.contractValue||0)}/></div><div className="field"><label>Status</label><select name="status" defaultValue={edit?.status||'ACTIVE'}><option>PLANNING</option><option>ACTIVE</option><option>ON_HOLD</option><option>DONE</option></select></div><div className="field" style={{gridColumn:'1/-1'}}><label>Keterangan</label><textarea name="description" defaultValue={edit?.description||''}/></div></div>{msg&&<p className="danger">{msg}</p>}<div className="formactions"><button type="button" className="btn secondary" onClick={()=>{setOpen(false);setEdit(null)}}>Batal</button><button className="btn">Simpan Project</button></div></form></div>}
  <div className="tablewrap section"><table><thead><tr><th>Kode</th><th>Nama Project</th><th>Nilai Kontrak</th><th>Status</th><th>Sinkronisasi</th><th>Aksi</th></tr></thead><tbody>{rows.length?rows.map(p=><tr key={p.id}><td><b>{p.code}</b></td><td>{p.name}</td><td>{Number(p.contractValue).toLocaleString('id-ID')}</td><td><span className="pill">{p.status}</span></td><td>{p.accurateId?<span className="pill green">Accurate ✓</span>:<span className="pill amber">Lokal</span>}</td><td><button className="btn small secondary" onClick={()=>form(p)}>Edit</button> {!p.accurateId&&pushConfigured&&<button className="btn small secondary" disabled={!!syncing} onClick={()=>push(p)}>{syncing===p.id?'Mengirim...':'Kirim ke Accurate'}</button>} <button className="btn small secondary" onClick={()=>del(p)}>Hapus</button></td></tr>):<tr><td colSpan={6} className="empty">Belum ada project. Klik “Project Baru” untuk mulai tanpa Accurate Online.</td></tr>}</tbody></table></div>
 </Page>
}
