'use client';
import {useState} from 'react';
type TopTab='Umum'|'RAB'|'Anggaran & Kuantitas'; type DetailTab='Bahan baku'|'Biaya Proyek'|'AHP'|'Catatan';
export default function RabWorkspace(){
 const [tab,setTab]=useState<TopTab>('RAB'); const [detail,setDetail]=useState<DetailTab>('Bahan baku'); const [selected,setSelected]=useState(2); const [rows,setRows]=useState([
  {no:'A',desc:'STRUKTUR',volume:'1',unit:'',type:'Grup'}, {no:'I',desc:'PEKERJAAN PONDASI DAN STRUKTUR',volume:'1',unit:'',type:'Grup'}, {no:'1',desc:'Pemasangan Bouwplank',volume:'100',unit:'m',type:'Pekerjaan'}]);
 const add=(type:'Grup'|'Pekerjaan')=>setRows(r=>[...r,{no:type==='Grup'?String.fromCharCode(65+r.filter(x=>x.type==='Grup').length):String(r.filter(x=>x.type==='Pekerjaan').length+1),desc:type==='Grup'?'GROUP BARU':'Pekerjaan baru',volume:'1',unit:type==='Grup'?'':'unit',type}]);
 const move=(dir:-1|1)=>{setRows(r=>{const n=[...r],to=selected+dir;if(to<0||to>=n.length)return r;[n[selected],n[to]]=[n[to],n[selected]];setSelected(to);return n})};
 return <>
 <div className="rab-head card"><div><label>No. Proyek</label><select className="input"><option>Pilih project dari Accurate...</option></select></div><div><label>Nama Proyek</label><input className="input" readOnly placeholder="Terisi dari master Project"/></div><div className="wide"><label>Keterangan</label><input className="input" placeholder="Keterangan RAB"/></div></div>
 <div className="tabs">{(['Umum','RAB','Anggaran & Kuantitas'] as TopTab[]).map(x=><button key={x} className={`tabbtn ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Umum'&&<div className="card"><h3>Informasi RAB</h3><p className="muted">Pilih project dari master Accurate Online dan isi keterangan RAB. Master Project tidak dibuat dari aplikasi ini.</p></div>}
 {tab==='Anggaran & Kuantitas'&&<div className="card"><h3>Anggaran & Kuantitas</h3><p className="muted">Ringkasan volume, kuantitas material, dan anggaran akan dihitung dari detail pekerjaan RAB.</p></div>}
 {tab==='RAB'&&<><div className="toolbar"><button className="btn" onClick={()=>add('Grup')}>+ Group Baru</button><button className="btn" onClick={()=>add('Pekerjaan')}>+ Pekerjaan Baru</button><label><input type="checkbox"/> RAB sudah ditel</label><span className="spacer"/><button className="btn secondary" onClick={()=>move(-1)}>↑ Geser atas</button><button className="btn secondary" onClick={()=>move(1)}>↓ Geser bawah</button></div>
 <div className="card rab-grid"><table><thead><tr><th>No</th><th>Deskripsi</th><th>Volume</th><th>Satuan</th><th>Fak. Vol</th><th>Fak. Barang</th><th>Fak. Upah</th><th>Harga</th><th>Tgl Mulai</th><th>Tgl Berakhir</th><th>Subkon.</th><th>Tipe</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>setSelected(i)} className={`${r.type==='Grup'?(i===0?'group':'group2'):''} ${selected===i?'selectedrow':''}`}><td>{r.no}</td><td>{r.desc}</td><td>{r.volume}</td><td>{r.unit}</td><td>1</td><td>1</td><td>1</td><td>Rp 0</td><td></td><td></td><td>{r.type==='Pekerjaan'?'☐':''}</td><td>{r.type}</td></tr>)}</tbody></table></div>
 <div className="rab-bottom"><div className="card detail"><div className="tabs small">{(['Bahan baku','Biaya Proyek','AHP','Catatan'] as DetailTab[]).map(x=><button key={x} className={`tabbtn ${detail===x?'active':''}`} onClick={()=>setDetail(x)}>{x}</button>)}</div>{detail==='Bahan baku'?<table><thead><tr><th>No. Barang</th><th>Deskripsi</th><th>Kuantitas</th><th>Satuan</th><th>Harga</th><th>Harga Total</th><th>WPA</th></tr></thead><tbody><tr><td colSpan={7} className="empty">Pilih pekerjaan lalu tambahkan Item dari master Accurate Online</td></tr></tbody></table>:<div className="empty">Panel {detail} untuk pekerjaan terpilih.</div>}</div><div className="card totals"><p><span>Sub Total</span><b>Rp 0</b></p><p><span>Kontraktor %</span><b>0</b></p><p><span>Total</span><b>Rp 0</b></p><p><span>Pembulatan</span><b>Rp 0</b></p><p><span>Servis Lain-lain</span><b>Rp 0</b></p><p><span>Penambahan</span><b>Rp 0</b></p><hr/><p className="grand"><span>Total seluruhnya</span><b>Rp 0</b></p><p><span>PPN</span><b>Rp 0</b></p></div></div></>}
 </>
}
