'use client';
import {useEffect,useState} from 'react';

type Kind='PR'|'PO'|'RECEIPT'|'INVOICE';
export default function TransactionCrud({kind,title}:{kind:Kind,title:string}){
 const [docs,setDocs]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[vendors,setVendors]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false);
 const [f,setF]=useState<any>({number:'',projectId:'',vendorId:'',itemId:'',qty:1,unitPrice:0,notes:''});
 const load=async()=>{const [d,p,v,i]=await Promise.all([fetch('/api/purchases?type='+kind).then(x=>x.json()),fetch('/api/projects').then(x=>x.json()),fetch('/api/vendors').then(x=>x.json()),fetch('/api/items').then(x=>x.json())]);setDocs(d);setProjects(p);setVendors(v);setItems(i)};
 useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();await fetch('/api/purchases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:kind,number:f.number,projectId:f.projectId,vendorId:f.vendorId||null,notes:f.notes,lines:[{itemId:f.itemId,description:items.find(x=>x.id===f.itemId)?.name||'',qty:+f.qty,unit:items.find(x=>x.id===f.itemId)?.unit,unitPrice:+f.unitPrice}]})});setOpen(false);setF({number:'',projectId:'',vendorId:'',itemId:'',qty:1,unitPrice:0,notes:''});load()}
 async function status(id:string,s:string){await fetch('/api/purchases',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:s})});load()}
 async function del(id:string){if(confirm('Hapus dokumen ini?')){await fetch('/api/purchases?id='+id,{method:'DELETE'});load()}}
 return <main className="content"><div className="page-title"><div><h1>{title}</h1><p>Transaksi terhubung ke Project, Item RAB, Vendor dan master Accurate.</p></div><button className="btn" onClick={()=>setOpen(!open)}>+ Tambah</button></div>
 {open&&<form className="panel form-grid" onSubmit={save}><label>No Dokumen<input required value={f.number} onChange={e=>setF({...f,number:e.target.value})}/></label><label>Project<select required value={f.projectId} onChange={e=>setF({...f,projectId:e.target.value})}><option value="">Pilih</option>{projects.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><label>Vendor<select value={f.vendorId} onChange={e=>setF({...f,vendorId:e.target.value})}><option value="">-</option>{vendors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Item<select required value={f.itemId} onChange={e=>setF({...f,itemId:e.target.value})}><option value="">Pilih</option>{items.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label><label>Qty<input type="number" step="any" value={f.qty} onChange={e=>setF({...f,qty:e.target.value})}/></label><label>Harga<input type="number" step="any" value={f.unitPrice} onChange={e=>setF({...f,unitPrice:e.target.value})}/></label><label>Catatan<input value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div><button className="btn" type="submit">Simpan</button></div></form>}
 <div className="panel table-wrap"><table><thead><tr><th>No</th><th>Tanggal</th><th>Project</th><th>Vendor</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.number}</td><td>{new Date(d.docDate).toLocaleDateString('id-ID')}</td><td>{d.project?.name}</td><td>{d.vendor?.name||'-'}</td><td>Rp {d.lines.reduce((a:number,l:any)=>a+Number(l.qty)*Number(l.unitPrice),0).toLocaleString('id-ID')}</td><td>{d.status}</td><td><button onClick={()=>status(d.id,'APPROVED')}>Approve</button> <button onClick={()=>status(d.id,'POSTED')}>Post</button> <button onClick={()=>del(d.id)}>Hapus</button></td></tr>)}</tbody></table>{!docs.length&&<p className="empty">Belum ada transaksi.</p>}</div></main>
}
