-- v7 data model: Accurate-owned masters + hierarchical RAB.
-- Early MVP migration: project/RAB/cost transactional tables are rebuilt.
DROP TABLE IF EXISTS "MaterialIssueItem" CASCADE;
DROP TABLE IF EXISTS "MaterialIssue" CASCADE;
DROP TABLE IF EXISTS "ProjectExpense" CASCADE;
DROP TABLE IF EXISTS "RabItem" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;

DO $$ BEGIN CREATE TYPE "RabRowType" AS ENUM ('GROUP','WORK'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE "Customer" ("id" TEXT PRIMARY KEY,"accurateId" TEXT NOT NULL UNIQUE,"code" TEXT,"name" TEXT NOT NULL,"lastSyncedAt" TIMESTAMP(3));
CREATE TABLE "Vendor" ("id" TEXT PRIMARY KEY,"accurateId" TEXT NOT NULL UNIQUE,"code" TEXT,"name" TEXT NOT NULL,"lastSyncedAt" TIMESTAMP(3));
CREATE TABLE "Item" ("id" TEXT PRIMARY KEY,"accurateId" TEXT NOT NULL UNIQUE,"code" TEXT,"name" TEXT NOT NULL,"unit" TEXT,"lastPrice" DECIMAL(18,2) NOT NULL DEFAULT 0,"lastSyncedAt" TIMESTAMP(3));
CREATE TABLE "Project" ("id" TEXT PRIMARY KEY,"accurateId" TEXT NOT NULL UNIQUE,"code" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"description" TEXT,"customerId" TEXT,"contractValue" DECIMAL(18,2) NOT NULL DEFAULT 0,"status" "ProjectStatus" NOT NULL DEFAULT 'ACTIVE',"lastSyncedAt" TIMESTAMP(3),CONSTRAINT "Project_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "RabHeader" ("id" TEXT PRIMARY KEY,"projectId" TEXT NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"notes" TEXT,"isDetailed" BOOLEAN NOT NULL DEFAULT true,"contractorPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,"rounding" DECIMAL(18,2) NOT NULL DEFAULT 0,"otherService" DECIMAL(18,2) NOT NULL DEFAULT 0,"addition" DECIMAL(18,2) NOT NULL DEFAULT 0,"taxPercent" DECIMAL(9,4) NOT NULL DEFAULT 11,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RabHeader_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "RabHeader_projectId_version_key" ON "RabHeader"("projectId","version");
CREATE TABLE "RabItem" ("id" TEXT PRIMARY KEY,"rabHeaderId" TEXT NOT NULL,"parentId" TEXT,"sortOrder" INTEGER NOT NULL DEFAULT 0,"code" TEXT NOT NULL,"rowType" "RabRowType" NOT NULL DEFAULT 'WORK',"description" TEXT NOT NULL,"volume" DECIMAL(18,4) NOT NULL DEFAULT 1,"unit" TEXT,"volumeFactor" DECIMAL(18,4) NOT NULL DEFAULT 1,"materialFactor" DECIMAL(18,4) NOT NULL DEFAULT 1,"laborFactor" DECIMAL(18,4) NOT NULL DEFAULT 1,"unitPrice" DECIMAL(18,2) NOT NULL DEFAULT 0,"startDate" TIMESTAMP(3),"endDate" TIMESTAMP(3),"subcontract" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "RabItem_rabHeaderId_fkey" FOREIGN KEY ("rabHeaderId") REFERENCES "RabHeader"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "RabItem_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "RabItem"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "RabItem_rabHeaderId_code_key" ON "RabItem"("rabHeaderId","code");
CREATE TABLE "RabMaterial" ("id" TEXT PRIMARY KEY,"rabItemId" TEXT NOT NULL,"itemId" TEXT NOT NULL,"qty" DECIMAL(18,4) NOT NULL,"unit" TEXT,"unitPrice" DECIMAL(18,2) NOT NULL,"wpa" DECIMAL(18,4) NOT NULL DEFAULT 0,CONSTRAINT "RabMaterial_rabItemId_fkey" FOREIGN KEY ("rabItemId") REFERENCES "RabItem"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "RabMaterial_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "MaterialIssue" ("id" TEXT PRIMARY KEY,"number" TEXT NOT NULL UNIQUE,"projectId" TEXT NOT NULL,"issueDate" TIMESTAMP(3) NOT NULL,"warehouseName" TEXT,"notes" TEXT,"status" "DocStatus" NOT NULL DEFAULT 'DRAFT',"accurateRef" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "MaterialIssue_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "MaterialIssueItem" ("id" TEXT PRIMARY KEY,"materialIssueId" TEXT NOT NULL,"rabItemId" TEXT NOT NULL,"accurateItemId" TEXT,"itemName" TEXT NOT NULL,"qty" DECIMAL(18,4) NOT NULL,"unit" TEXT NOT NULL,"actualUnitCost" DECIMAL(18,2) NOT NULL DEFAULT 0,"actualCost" DECIMAL(18,2) NOT NULL DEFAULT 0,CONSTRAINT "MaterialIssueItem_materialIssueId_fkey" FOREIGN KEY ("materialIssueId") REFERENCES "MaterialIssue"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "MaterialIssueItem_rabItemId_fkey" FOREIGN KEY ("rabItemId") REFERENCES "RabItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "ProjectExpense" ("id" TEXT PRIMARY KEY,"number" TEXT NOT NULL UNIQUE,"projectId" TEXT NOT NULL,"rabItemId" TEXT,"expenseDate" TIMESTAMP(3) NOT NULL,"type" "CostType" NOT NULL,"vendorName" TEXT,"description" TEXT NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"status" "DocStatus" NOT NULL DEFAULT 'DRAFT',"accurateRef" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProjectExpense_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT "ProjectExpense_rabItemId_fkey" FOREIGN KEY ("rabItemId") REFERENCES "RabItem"("id") ON DELETE SET NULL ON UPDATE CASCADE);
